import "./globals.css";
import type { Metadata } from "next";
import { Inter, JetBrains_Mono, Open_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/themes-provider";
import { ModalProvider } from "@/components/providers/modal-provider";
import { AppProviders } from "@/components/providers/app-providers";
import { SocketProvider } from "@/components/providers/socket-provider";
import SocketInit from "./socket-init";
import { QueryProvider } from "@/components/providers/query-provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const mono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Platform Kolaborasi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        suppressHydrationWarning
        className={cn(inter.variable, mono.variable, "h-full")}
      >
        <body
          suppressHydrationWarning
          className={cn(openSans.className, "h-full")}
        >
          <SocketInit />
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="platform-theme"
          >
            <SocketProvider>
              <AppProviders>
                <ModalProvider />
                <QueryProvider>
                  {children}
                </QueryProvider>
              </AppProviders>
            </SocketProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}